test/test_stdlib.rb

Per #12.
> that checking the main constant is enough.
Agreed.
1. Somehow deleted openssl from my gist.  Added for this PR.
2. For the four libraries that have 'external' version info, I added the constant.  Seemed like a handy place to have them...

Update tests for std-lib ext objects

---

lib/ruby_installer/runtime/components/01_msys2.rb

Fixes a ~critical bug~ minor spelling issue in msys2 error logging.

Fix typo in msys2 component

---

lib/ruby_installer/build/msys2_installation.rb

[Scoop](https://github.com/lukesampson/scoop) is a command-line installer for Windows like chocolatey.
The scoop-managed msys2 could be detected by `scoop prefix msys2` that returns the path to the specified app.
Fix https://github.com/ScoopInstaller/Main/issues/271

Detect scoop-managed msys2

---

lib/ruby_installer/runtime/ridk.rb

set $VERBOSE to nil in ignore_err

ridk.rb - add CC_VERSION_MESSAGE to 'ridk version', remove warnings

---

lib/ruby_installer/build/dll_directory.rb

Fiddle's default is to not free the allocated memory by the GC, so this fixes a small memory leak.

Ensure DllDirectory frees the memory it alloced

---

recipes/installer-inno/ri_gui.iss

[1] As mentioned by @larskanis at http://disq.us/p/2ee06yv - the URL for the wiki in the GUI is incorrect. This just changes the URLText to the correct link.
[2] Also, changes the TextURL for RubyInstaller.org & Google Groups to https instead of http

Fix URLs in the Installer WizardForm.FinishedPage

---

.github/workflows/ci.yml

Also use latest ruby-spec for ruby-3.0.2, since ruby-spec promise to succeed on latest stable ruby releases.

CI: Update build-ruby versions for Github Actions

---

CHANGELOG-2.5.md
CHANGELOG-2.6.md
CHANGELOG-2.7.md
CHANGELOG-3.0.md

Cleans up a few typos. A few of the recent entries on the releases page have incorrect dates too.
Thanks for everything you do in this project!

Fix recent release dates in changelogs

---

lib/ruby_installer/build/msys2_installation.rb

I use Ruby 27 2.7.4-1 x64 msvcrt and running WEBrick.
When run the CGI program, I got a runtime error in msys2_installation.rb.
error message is here.
```
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:76:in `iterate_msys_paths': undefined method `split' for nil:NilClass (NoMethodError)
```
When running the CGI program, the ENV environment variables were rewritten to the values for CGI.
e.g.
```
{"GATEWAY_INTERFACE"=>"CGI/1.1", "HTTP_ACCEPT"=>"text/html,application..."}
```

Fix a runtime error when running cgi in WEBrick http server.

---

lib/ruby_installer/build/msys2_installation.rb

prefer ENV["MSYS2_PATH"] if set for #iterate_msys_paths

Update msys2_installation.rb #iterate_msys_paths

---

test/test_win32-registry.rb

So do ensure code only after chcp

ensure path caused failure in skip-case

---

resources/files/operating_system.rb

We're getting some [test failures ](https://github.com/rubygems/rubygems/actions/runs/7708963464/job/21009146956?pr=7438) in rubygems because we run `gem` commands in verbose mode, in situations where the default GEM_HOME is not writable.
I'm not sure of the root cause (why GEM_HOME is not writable), since it only happens sporadically so I guess some other specs may be leaking permission changes or something. Also we could probably switch those to run in non verbose mode, or manually skip the warnings. But it seems best to not let the warning be printed in the first place, since that's exactly what's intended here.
This PR is a hack to achieve that.

Avoid method redefinition warning

---

lib/ruby_installer/build/msys2_installation.rb

When the registry key `SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` contains inconvertible characters to internal encoding, `require rubygems` crashes. This patch avoids this issue.
Fixe #372

Avoid crash even if a registry key incldues inconvertible characters

---

CHANGELOG-3.2.md
CHANGELOG-3.3.md
recipes/sandbox/70-move-openssl-files-to-bin.rake
recipes/sandbox/rubyinstaller-3.2.4.files
recipes/sandbox/rubyinstaller-3.3.1.files
recipes/sandbox/rubyinstaller-head.files
test/test_stdlib.rb

This is necessary because libcrypt.dll and libssl.dll are located in bin/ruby_builtin_dlls and they search other dlls in ../lib
Fixes #365

Move bundled OpenSSL related files to bin/lib subdirectory.

---

resources/files/operating_system.rb

The previous "{}" literal closed the root hash, so that appending text to the file doesn't work easily. But it's the only way to set an empty hash.
As a solution, we set a single key now.
This was raised in https://github.com/oneclick/rubyinstaller2/issues/388#issuecomment-2348393612

Set a single key in gemrc to allow appending

---

lib/ruby_installer/build/msys2_installation.rb
test/helper/testgem/Gemfile
test/helper/testgem/ext2/extconf2.rb
test/helper/testgem/ext2/testgem2.c
test/helper/testgem/testgem2.gemspec
test/test_gem_install.rb

pacman invocation must be serialized to avoid locking error.
Add a second gem using libidn2, so that two different libraries are requested and the test case fails if anyone isn't available after parallel pacman execution.
The test case requires bundler-2.6.x to trigger the failure due to https://github.com/rubygems/rubygems/pull/8248 .
Fixes #397

Fix pacman install within a parallel bundler install -jX

---

recipes/installer-inno/rubyinstaller.iss.erb
recipes/sandbox/10-define-variables.rake
recipes/sandbox/20-define-import-files.rake
resources/ssl/README-SSL.md

Now the certs are stored under `<ruby>/lib/...` and `<ruby>/ssl` is linked to this directory per innosetup installer.
Before this commit, the link was the other way around, but junctions can not be stored/restored in a 7z archive. This led to certs not found when 7z archive was used, like in ruby/setup-ruby.
Fixes #405

Reverse the junction/link to "ssl" dir

---

recipes/installer-inno/events.iss
recipes/installer-inno/util.iss

So far the uninstaller only removed the ruby install files, but kept the installed gems and MSYS2.
This is the right behaviour for an update installation, which uninstalls the previous ruby in the install directory first.
But it is not expected, when uninstalling from "Add/Remove Programs".
Also Microsoft Store requires to remove all related files.

Remove installed gems and MSYS2 from devkit by the uninstaller

---

.github/workflows/ci.yml
recipes/sandbox/rubyinstaller-3.4.1-x64-ucrt.files
recipes/sandbox/rubyinstaller-3.4.1-x86-msvcrt.files
recipes/sandbox/rubyinstaller-3.4.1.files

Building the installer works on x64, but it can not be tested without native ARM64 runner.

CI: Add arm builds to the matrix

---

.github/workflows/ci.yml

It is still applicable with the bundled json version, but our tests run after `bundle update` installed a newer version.

Exclude spec which is no longer applicable since json-2.11

---

test/helper/testgem/ext/extconf.rb

This is to test for the following issue: https://github.com/oneclick/rubyinstaller2/issues/439
Error is:
```
In file included from C:/Ruby34-x64/include/ruby-3.4.0/ruby/defines.h:74,
from C:/Ruby34-x64/include/ruby-3.4.0/ruby/ruby.h:25,
from C:/Ruby34-x64/include/ruby-3.4.0/ruby.h:38,
from conftest.c:1:
C:/msys64/ucrt64/include/stralign.h: In function 'ua_CharUpperW': C:/Ruby34-x64/include/ruby-3.4.0/ruby/backward/2/bool.h:31:15: error: 'true' undeclared (first use in this function)
31 | # define TRUE true
|               ^~~~
In file included from C:/msys64/ucrt64/include/windows.h:114,
from C:/msys64/ucrt64/include/winsock2.h:23,
from C:/Ruby34-x64/include/ruby-3.4.0/ruby/win32.h:36,
from C:/Ruby34-x64/include/ruby-3.4.0/ruby/internal/dosish.h:38,
from …
```

Use C99 in testgem to trigger issue with stdbool
